CREATE TABLE person (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE address (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    person_id BIGINT,
    city VARCHAR(255) NOT NULL,
    FOREIGN KEY (person_id) REFERENCES person(id)
);
